invoiceNumber = "INV-2025-001"
issueDate = "2025-08-05"
dueDate = "2025-08-19"
status = "DRAFT"
notes = "Vielen Dank für Ihren Einkauf.\nBitte überweisen Sie den Betrag innerhalb von 14 Tagen.\nSonderzeichen: äöüß'\"<>&"
subtotal = "5642.86"
tax = "1072.1434"
total = "6715.0034"
companyLogo = "kJ4RtXmmjz+rcxqT7csuwcg4aPAnuoziS/yHKGdfuwhTx3s/U2zjlM48VyjbvUCHipdf8zy6CKtl06M4k7Akbr4AbUqZnFrC0UbfdH/sBjOxQEeEAh3FkfL5ggU0wMzrSCvcdI7d2DCeRLXlOB6rhX2hk2e89s+4tMXmF3yHUIaaA4uwlk9o43BCKu0pmmQYoxLZLRPUSID/plrMn0ir2xP1qbm9LRmlVvxHa7n8dRnLUsqek+LJpD5nXRZWK+3nR7wzLy/+BIqzhL8vFRxhhhLRm8YrqZ3Vb7cDz1/peOp82SqdwVJXDsA6loOp/AJuiceVn7FQw5miDu7m+oqaryvTIgVnGX7YCRELdqvViam0Jd8AXHwDeX3YqzRtM4lqhUi/1Lx84+XsI27dkCV3pwtLy9JIspcEu/Pl4YL9Jfzs0xLFfVTTsx2g5JmV1h9YfJE0iPZTJomogOqqBOgJ+3W9B9EOJm7IJflSrTdzXAfnp62DySYV6qf/cz1F0rQRbX08TPO0y9neb+cou2pb86G8k16JbHRkrL/FBJuI70/RDv4mWCOvs/no/sWnZce88ndL/+SLBL7DnHea3+Cy3NQRSpeKom7meBNePUeqs2CXxjIL6EgYs4cOi+Ts5iUOXb4Csnyz8Ds03/gUKZEASUB0EYiLjVVMq4ajoiYZhU2Gpr76Q/fg6VhDwqmhCSokE5YScCPCliN1H3zN8LQEVR5J3pOaj3565FQ+sEYusqEnxZCS7rVuhT6a9LQ0EwBGKHTRg18Ppm8rrdBDc+mZ5AopP1uMFxHL861POuAUCM5ad7Z3FPv4tVUgAeLHqZl5PFJ5AH99oT6XpXzdY5+iEZ8mvYZf2UQY3sMwXKUmDOOy5MMosv4qWr9OhpU0Kc1blaz3vIrTiwUVRXnftTS9WFQSyE7vWsI3FDiBlUxWlKEQLYOfBOZQJp6PsK9hqg4ufuVTCmezlJfVP5MwpqRSwZU3Mm/doAlw8MPKF1lUJW2DWynsL9Pk9lJy7gjGKGgF4Akjqk5415/YfRRfD/oPmiVPpsm9BznRcjjZli9afdpfousvL6XqR/Vq/0c8cho9HzOPLG+JO0su1h3e7O+i2bSiRXd/lTDlOTF7ulnHvsebnIYaBHQPNRM5e9kIzeA+NgJkd+HsL8VupRTBJ2zmo7yd+44gTxyIxBbxvBb9BaVxkFxCGRU03q9RVe0ogG3BFvCY0c0mkkJ2WwGxqcDLZ6FHT9GSXioe6ksdjSMkGsIx735K9TMoyXPoQBLdqZ1dO281Ltuw0h5lXPHXpN55+Alj0pTpFNjFmKLRkc3ImLJljoL6JcsloDZ0d2B5EFfKkRpqV92Vl9DW0J/MGuiTjg=="

[billingAddress]
street = "Musterstrasse 123"
city = "Musterstadt"
postalCode = "12345"
country = "Deutschland"

[[lineItems]]
productId = "PROD-1000"
description = "Produkt 1 mit einer Beschreibung."
quantity = 7
unitPrice = "29.85"
lineTotal = "208.95"

[[lineItems]]
productId = "PROD-1001"
description = "Produkt 2 mit einer Beschreibung."
quantity = 4
unitPrice = "100.44"
lineTotal = "401.76"

[[lineItems]]
productId = "PROD-1002"
description = "Produkt 3 mit einer Beschreibung."
quantity = 5
unitPrice = "89.91"
lineTotal = "449.55"

[[lineItems]]
productId = "PROD-1003"
description = "Produkt 4 mit einer Beschreibung."
quantity = 8
unitPrice = "95.15"
lineTotal = "761.20"

[[lineItems]]
productId = "PROD-1004"
description = "Produkt 5 mit einer Beschreibung."
quantity = 10
unitPrice = "89.76"
lineTotal = "897.60"

[[lineItems]]
productId = "PROD-1005"
description = "Produkt 6 mit einer Beschreibung."
quantity = 2
unitPrice = "14.90"
lineTotal = "29.80"

[[lineItems]]
productId = "PROD-1006"
description = "Produkt 7 mit einer Beschreibung."
quantity = 4
unitPrice = "85.04"
lineTotal = "340.16"

[[lineItems]]
productId = "PROD-1007"
description = "Produkt 8 mit einer Beschreibung."
quantity = 9
unitPrice = "16.95"
lineTotal = "152.55"

[[lineItems]]
productId = "PROD-1008"
description = "Produkt 9 mit einer Beschreibung."
quantity = 5
unitPrice = "18.77"
lineTotal = "93.85"

[[lineItems]]
productId = "PROD-1009"
description = "Produkt 10 mit einer Beschreibung."
quantity = 6
unitPrice = "106.04"
lineTotal = "636.24"

[[lineItems]]
productId = "PROD-1010"
description = "Produkt 11 mit einer Beschreibung."
quantity = 2
unitPrice = "101.63"
lineTotal = "203.26"

[[lineItems]]
productId = "PROD-1011"
description = "Produkt 12 mit einer Beschreibung."
quantity = 5
unitPrice = "104.83"
lineTotal = "524.15"

[[lineItems]]
productId = "PROD-1012"
description = "Produkt 13 mit einer Beschreibung."
quantity = 7
unitPrice = "38.97"
lineTotal = "272.79"

[[lineItems]]
productId = "PROD-1013"
description = "Produkt 14 mit einer Beschreibung."
quantity = 6
unitPrice = "88.70"
lineTotal = "532.20"

[[lineItems]]
productId = "PROD-1014"
description = "Produkt 15 mit einer Beschreibung."
quantity = 10
unitPrice = "13.88"
lineTotal = "138.80"
